scripts: Use language configuration file

diff --git a/po/scripts/l10n_set b/po/scripts/l10n_set
--- a/po/scripts/l10n_set
+++ b/po/scripts/l10n_set
@@ -1,18 +1,11 @@
-lname="Unknown"
-case $lcode in
-    cs) lname="Czech";;
-    da) lname="Danish";;
-    de) lname="German";;
-    es) lname="Spanish";;
-    fa) lname="Persian";;
-    fr) lname="French";;
-    hu) lname="Hungarian";;
-    it) lname="Italian";;
-    mk) lname="Macedonian";;
-    nl) lname="Dutch";;
-    pl) lname="Polish";;
-    pt_BR) lname="Brazilian Portugues";;
-    ro) lname="Romanian";;
-    sr) lname="Serbian";;
-esac
+langname="Unknown"
+
+cfname=$lcode.config
+
+if [ -f ../scripts/$cfname ]; then
+    source ../scripts/$cfname
+else
+    echo "Configuration for $lcode not found"
+    exit 2
+fi
 
