scripts: Reverse test
It makes more sense to first test if we are in the language directory
and only then to assume we are outside (i.e. in scripts)

diff --git a/po/scripts/l10n_test b/po/scripts/l10n_test
--- a/po/scripts/l10n_test
+++ b/po/scripts/l10n_test
@@ -15,20 +15,19 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if [ a"$1" != a ]; then
+if [ -d man1 ]; then
+    lcode=$(basename $(pwd))
+elif [ a"$1" != a ]; then
     if [ -d ../$1 ]; then
         cd ../$1
+        lcode=$1
     else
         echo "Language $1 could not be found, aborting"
         exit 1
     fi
-    lcode=$1
 else
-    if [ ! -d man1 ]; then
-        echo "No directories with man pages found, aborting"
-        exit 2
-    fi
-    lcode=$(basename $(pwd))
+    echo "Could not determine target directory, aborting"
+    exit 2
 fi
 
 #cat ../scripts/l10n_set
