reportupstream: Add some basic error checking

diff --git a/upstreambug/reportupstream b/upstreambug/reportupstream
--- a/upstreambug/reportupstream
+++ b/upstreambug/reportupstream
@@ -27,11 +27,44 @@ DIALOG=$(which dialog)
 sk_temp=$((tempfile) 2>/dev/null)
 SSF_MAILER=/usr/bin/mutt
 SSF_BROWSER=/usr/bin/firefox
+SSF_TMP=/tmp/ssf
 
 # Allow to customize these variables if necessary
 if [ -f $HOME/.config/reportupstreamrc ] ; then
     echo "Sourcing local config"
     . $HOME/.config/reportupstreamrc
+fi
+
+# Check if the files and directories exist
+
+if [ ! -d $DCSBASE ]; then
+    echo "Could not find the git repository directory for manpages-l10n under $DCSBASE"
+    exit
+fi
+
+if [ ! -x $DIALOG ]; then
+    echo "Could not find the the dialog program (or not executable) $DIALOG"
+    exit
+fi
+
+if [ ! -x $SSF_MAILER ]; then
+    echo "Could not find the the mail program (or not executable) $SSF_MAILER"
+    exit
+fi
+
+if [ ! -x $SSF_BROWSER ]; then
+    echo "Could not find the the mail program (or not executable) $SSF_BROWSER"
+    exit
+fi
+
+if [ ! -d $SSF_TMP ]; then
+    mkdir -p $SSF_TMP
+    retval=$?
+
+    if [ $retval != 0 ]; then
+	echo "Dirctory for tempory files $SSF_TMP does not exist and cannot be created"
+	exit
+    fi
 fi
 
 cd $DCSBASE/po
