reportupstream: Remove temporary directory on request

diff --git a/upstreambug/reportupstream b/upstreambug/reportupstream
--- a/upstreambug/reportupstream
+++ b/upstreambug/reportupstream
@@ -192,6 +192,18 @@ while [ $ssf_STOP -eq 0 ]; do
     fi
 done
 
+echo "Should the temporary directory $SSF_TMP be removed?"
+read -p "(y/n)> "
+if [ $REPLY == "y" ]; then
+    rm -r $SSF_TMP
+    retval=$?
+
+    if [ $retval != 0 ]; then
+	echo "Dirctory for tempory files $SSF_TMP could not be removed."
+        exit
+    fi
+fi
+
 clear
 
 # A10 is not enough :-((
